version: "3"
services:
  db:
    image: mdillon/postgis:11-alpine
    container_name: test.db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 123456
    volumes:
      - db-data:/var/lib/postgresql/testdata

volumes:
  db-data:
